using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Box.V2.Services;
using Box.V2.Contracts;
using Box.V2.Auth;
using Box.V2.Models;
using System.Threading.Tasks;
using Box.V2.Managers;

namespace Box.V2.Test
{
    [TestClass]
    public class BoxFoldersManagerTest : BoxResourceManagerTest
    {

        [TestMethod]
        public async Task GetFolder_ValidResponse_ValidFolder()
        {
            _handler.Setup(h => h.ExecuteAsync<Folder>(It.IsAny<IBoxRequest>()))
                .Returns(() => Task.FromResult<IBoxResponse<Folder>>(new BoxResponse<Folder>()
                    {
                        Status = ResponseStatus.Success,
                        //ContentString = "{ \"type\": \"folder\", \"id\": \"11446498\", \"sequence_id\": \"1\", \"etag\": \"1\", \"name\": \"Pictures\", \"created_at\": \"2012-12-12T10:53:43-08:00\", \"modified_at\": \"2012-12-12T11:15:04-08:00\", \"description\": \"Some pictures I took\", \"size\": 629644, \"path_collection\": { \"total_count\": 1, \"entries\": [ { \"type\": \"folder\", \"id\": \"0\", \"sequence_id\": null, \"etag\": null, \"name\": \"All Files\" } ] }, \"created_by\": { \"type\": \"user\", \"id\": \"17738362\", \"name\": \"sean rose\", \"login\": \"sean@box.com\" }, \"modified_by\": { \"type\": \"user\", \"id\": \"17738362\", \"name\": \"sean rose\", \"login\": \"sean@box.com\" }, \"owned_by\": { \"type\": \"user\", \"id\": \"17738362\", \"name\": \"sean rose\", \"login\": \"sean@box.com\" }, \"shared_link\": { \"url\": \"https://www.box.com/s/vspke7y05sb214wjokpk\", \"download_url\": \"https://www.box.com/shared/static/vspke7y05sb214wjokpk\", \"vanity_url\": null, \"is_password_enabled\": false, \"unshared_at\": null, \"download_count\": 0, \"preview_count\": 0, \"access\": \"open\", \"permissions\": { \"can_download\": true, \"can_preview\": true } }, \"folder_upload_email\": { \"access\": \"open\", \"email\": \"upload.Picture.k13sdz1@u.box.com\" }, \"parent\": { \"type\": \"folder\", \"id\": \"0\", \"sequence_id\": null, \"etag\": null, \"name\": \"All Files\" }, \"item_status\": \"active\", \"item_collection\": { \"total_count\": 1, \"entries\": [ { \"type\": \"file\", \"id\": \"5000948880\", \"sequence_id\": \"3\", \"etag\": \"3\", \"sha1\": \"134b65991ed521fcfe4724b7d814ab8ded5185dc\", \"name\": \"tigers.jpeg\" } ], \"offset\": 0, \"limit\": 100 } }"
                        //ContentString = "{\"type\":\"folder\",\"id\":\"0\",\"sequence_id\":null,\"etag\":null,\"name\":\"All Files\",\"created_at\":null,\"modified_at\":null,\"description\":\"\",\"size\":61591428468,\"path_collection\":{\"total_count\":0,\"entries\":[]},\"created_by\":{\"type\":\"user\",\"id\":\"189912110\",\"name\":\"Brian\",\"login\":\"brianytang@gmail.com\"},\"modified_by\":{\"type\":\"user\",\"id\":\"189912110\",\"name\":\"Brian\",\"login\":\"brianytang@gmail.com\"},\"trashed_at\":null,\"purged_at\":null,\"content_created_at\":null,\"content_modified_at\":null,\"owned_by\":{\"type\":\"user\",\"id\":\"189912110\",\"name\":\"Brian\",\"login\":\"brianytang@gmail.com\"},\"shared_link\":null,\"folder_upload_email\":null,\"parent\":null,\"item_status\":\"active\",\"item_collection\":{\"total_count\":10,\"entries\":[{\"type\":\"folder\",\"id\":\"766352168\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Books\"},{\"type\":\"folder\",\"id\":\"869883498\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"bytLabs\"},{\"type\":\"folder\",\"id\":\"767221958\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Games\"},{\"type\":\"folder\",\"id\":\"766174084\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Mixes\"},{\"type\":\"folder\",\"id\":\"57181304\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Muzik\"},{\"type\":\"folder\",\"id\":\"857305570\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"My\"},{\"type\":\"folder\",\"id\":\"627316229\",\"sequence_id\":\"1\",\"etag\":\"1\",\"name\":\"My Music Folder\"},{\"type\":\"folder\",\"id\":\"860155462\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"sample\"},{\"type\":\"folder\",\"id\":\"775829294\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Software\"},{\"type\":\"folder\",\"id\":\"811565831\",\"sequence_id\":\"0\",\"etag\":\"0\",\"name\":\"Test\"}],\"offset\":0,\"limit\":10,\"order\":[{\"by\":\"type\",\"direction\":\"ASC\"},{\"by\":\"name\",\"direction\":\"ASC\"}]}}"
                        ContentString = "{ \"type\":\"folder\", \"id\":\"0\", \"sequence_id\":null, \"etag\":null, \"name\":\"All Files\", \"created_at\":null, \"modified_at\":null, \"description\":\"\", \"size\":61591428468, \"path_collection\":{ \"total_count\":0, \"entries\":[ ] }, \"created_by\":{ \"type\":\"user\", \"id\":\"189912110\", \"name\":\"Brian\", \"login\":\"brianytang@gmail.com\" }, \"modified_by\":{ \"type\":\"user\", \"id\":\"189912110\", \"name\":\"Brian\", \"login\":\"brianytang@gmail.com\" }, \"trashed_at\":null, \"purged_at\":null, \"content_created_at\":null, \"content_modified_at\":null, \"owned_by\":{ \"type\":\"user\", \"id\":\"189912110\", \"name\":\"Brian\", \"login\":\"brianytang@gmail.com\" }, \"shared_link\":null, \"folder_upload_email\":null, \"parent\":null, \"item_status\":\"active\", \"item_collection\":{ \"total_count\":10, \"entries\":[ { \"type\":\"folder\", \"id\":\"766352168\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Books\" }, { \"type\":\"folder\", \"id\":\"869883498\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"bytLabs\" }, { \"type\":\"folder\", \"id\":\"767221958\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Games\" }, { \"type\":\"folder\", \"id\":\"766174084\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Mixes\" }, { \"type\":\"folder\", \"id\":\"57181304\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Muzik\" }, { \"type\":\"folder\", \"id\":\"857305570\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"My\" }, { \"type\":\"folder\", \"id\":\"627316229\", \"sequence_id\":\"1\", \"etag\":\"1\", \"name\":\"My Music Folder\" }, { \"type\":\"folder\", \"id\":\"860155462\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"sample\" }, { \"type\":\"folder\", \"id\":\"775829294\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Software\" }, { \"type\":\"folder\", \"id\":\"811565831\", \"sequence_id\":\"0\", \"etag\":\"0\", \"name\":\"Test\" } ], \"offset\":0, \"limit\":10, \"order\":[ { \"by\":\"type\", \"direction\":\"ASC\" }, { \"by\":\"name\", \"direction\":\"ASC\" } ] } }"
                    }));

            Folder f = await _foldersManager.GetItemsAsync("0", 10);
        }
    }
}
