using System.ComponentModel;
using Box.Sdk.Gen.Schemas;
using Box.Sdk.Gen.Internal;

namespace Box.Sdk.Gen.Schemas {
    public enum EventEventTypeField {
        [Description("ACCESS_GRANTED")]
        AccessGranted,
        [Description("ACCESS_REVOKED")]
        AccessRevoked,
        [Description("ADD_DEVICE_ASSOCIATION")]
        AddDeviceAssociation,
        [Description("ADD_LOGIN_ACTIVITY_DEVICE")]
        AddLoginActivityDevice,
        [Description("ADMIN_LOGIN")]
        AdminLogin,
        [Description("ADVANCED_FOLDER_SETTINGS_UPDATE")]
        AdvancedFolderSettingsUpdate,
        [Description("AI_SECURITY_DETECTION")]
        AiSecurityDetection,
        [Description("ANNOTATIONV2_CREATE")]
        Annotationv2Create,
        [Description("ANNOTATIONV2_DELETE")]
        Annotationv2Delete,
        [Description("ANNOTATIONV2_EDIT")]
        Annotationv2Edit,
        [Description("APPLICATION_CREATED")]
        ApplicationCreated,
        [Description("APPLICATION_PUBLIC_KEY_ADDED")]
        ApplicationPublicKeyAdded,
        [Description("APPLICATION_PUBLIC_KEY_DELETED")]
        ApplicationPublicKeyDeleted,
        [Description("BOX_AI_USER_FAILED_REQUEST")]
        BoxAiUserFailedRequest,
        [Description("BOX_AI_USER_REQUEST")]
        BoxAiUserRequest,
        [Description("CHANGE_ADMIN_ROLE")]
        ChangeAdminRole,
        [Description("CHANGE_FOLDER_PERMISSION")]
        ChangeFolderPermission,
        [Description("COLLABORATION_ACCEPT")]
        CollaborationAccept,
        [Description("COLLABORATION_EXPIRATION")]
        CollaborationExpiration,
        [Description("COLLABORATION_INVITE")]
        CollaborationInvite,
        [Description("COLLABORATION_REMOVE")]
        CollaborationRemove,
        [Description("COLLABORATION_ROLE_CHANGE")]
        CollaborationRoleChange,
        [Description("COLLAB_ADD_COLLABORATOR")]
        CollabAddCollaborator,
        [Description("COLLAB_INVITE_COLLABORATOR")]
        CollabInviteCollaborator,
        [Description("COLLAB_REMOVE_COLLABORATOR")]
        CollabRemoveCollaborator,
        [Description("COLLAB_ROLE_CHANGE")]
        CollabRoleChange,
        [Description("COLLECTION_CREATE")]
        CollectionCreate,
        [Description("COLLECTION_DELETE")]
        CollectionDelete,
        [Description("COLLECTION_ITEM_CREATE")]
        CollectionItemCreate,
        [Description("COLLECTION_ITEM_DELETE")]
        CollectionItemDelete,
        [Description("COLLECTION_ITEM_UPDATE")]
        CollectionItemUpdate,
        [Description("COLLECTION_UPDATE")]
        CollectionUpdate,
        [Description("COMMENT_CREATE")]
        CommentCreate,
        [Description("COMMENT_DELETE")]
        CommentDelete,
        [Description("COMMENT_EDIT")]
        CommentEdit,
        [Description("CONTENT_ACCESS")]
        ContentAccess,
        [Description("CONTENT_RECOVERY_REPORT_CREATE")]
        ContentRecoveryReportCreate,
        [Description("CONTENT_RECOVERY_REPORT_DELETE")]
        ContentRecoveryReportDelete,
        [Description("CONTENT_RECOVERY_REPORT_INITIATE")]
        ContentRecoveryReportInitiate,
        [Description("CONTENT_WORKFLOW_ABNORMAL_DOWNLOAD_ACTIVITY")]
        ContentWorkflowAbnormalDownloadActivity,
        [Description("CONTENT_WORKFLOW_AUTOMATION_ADD")]
        ContentWorkflowAutomationAdd,
        [Description("CONTENT_WORKFLOW_AUTOMATION_DELETE")]
        ContentWorkflowAutomationDelete,
        [Description("CONTENT_WORKFLOW_POLICY_ADD")]
        ContentWorkflowPolicyAdd,
        [Description("CONTENT_WORKFLOW_SHARING_POLICY_VIOLATION")]
        ContentWorkflowSharingPolicyViolation,
        [Description("CONTENT_WORKFLOW_UPLOAD_POLICY_VIOLATION")]
        ContentWorkflowUploadPolicyViolation,
        [Description("COPY")]
        Copy,
        [Description("DATA_RETENTION_CREATE_RETENTION")]
        DataRetentionCreateRetention,
        [Description("DATA_RETENTION_REMOVE_RETENTION")]
        DataRetentionRemoveRetention,
        [Description("DELETE")]
        Delete,
        [Description("DELETE_USER")]
        DeleteUser,
        [Description("DEVICE_TRUST_CHECK_FAILED")]
        DeviceTrustCheckFailed,
        [Description("DISABLE_MULTI_FACTOR_AUTH")]
        DisableMultiFactorAuth,
        [Description("DOWNLOAD")]
        Download,
        [Description("EDIT")]
        Edit,
        [Description("EDIT_USER")]
        EditUser,
        [Description("EDR_CROWDSTRIKE_ACCESS_ALLOWED_NO_CROWDSTRIKE_DEVICE")]
        EdrCrowdstrikeAccessAllowedNoCrowdstrikeDevice,
        [Description("EDR_CROWDSTRIKE_ACCESS_REVOKED")]
        EdrCrowdstrikeAccessRevoked,
        [Description("EDR_CROWDSTRIKE_BOX_TOOLS_OUTDATED")]
        EdrCrowdstrikeBoxToolsOutdated,
        [Description("EDR_CROWDSTRIKE_DEVICE_DETECTED")]
        EdrCrowdstrikeDeviceDetected,
        [Description("EDR_CROWDSTRIKE_DRIVE_OUTDATED")]
        EdrCrowdstrikeDriveOutdated,
        [Description("EDR_CROWDSTRIKE_NO_BOX_TOOLS")]
        EdrCrowdstrikeNoBoxTools,
        [Description("EMAIL_ALIAS_CONFIRM")]
        EmailAliasConfirm,
        [Description("EMAIL_ALIAS_PRIMARY")]
        EmailAliasPrimary,
        [Description("EMAIL_ALIAS_REMOVE")]
        EmailAliasRemove,
        [Description("EMAIL_UPLOAD_DISABLED")]
        EmailUploadDisabled,
        [Description("EMAIL_UPLOAD_ENABLED")]
        EmailUploadEnabled,
        [Description("ENABLE_MULTI_FACTOR_AUTH")]
        EnableMultiFactorAuth,
        [Description("ENABLE_TWO_FACTOR_AUTH")]
        EnableTwoFactorAuth,
        [Description("ENTERPRISE_APP_AUTHORIZATION_UPDATE")]
        EnterpriseAppAuthorizationUpdate,
        [Description("EXTERNAL_COLLAB_SECURITY_SETTINGS")]
        ExternalCollabSecuritySettings,
        [Description("FAILED_LOGIN")]
        FailedLogin,
        [Description("FAVORITE")]
        Favorite,
        [Description("FILE_MARKED_MALICIOUS")]
        FileMarkedMalicious,
        [Description("FILE_REQUEST_CREATE")]
        FileRequestCreate,
        [Description("FILE_REQUEST_DELETE")]
        FileRequestDelete,
        [Description("FILE_REQUEST_UPDATE")]
        FileRequestUpdate,
        [Description("FILE_VERSION_RESTORE")]
        FileVersionRestore,
        [Description("FILE_WATERMARKED_DOWNLOAD")]
        FileWatermarkedDownload,
        [Description("GROUP_ADD_ITEM")]
        GroupAddItem,
        [Description("GROUP_ADD_USER")]
        GroupAddUser,
        [Description("GROUP_ADMIN_CREATED")]
        GroupAdminCreated,
        [Description("GROUP_ADMIN_DELETED")]
        GroupAdminDeleted,
        [Description("GROUP_ADMIN_PERMISSIONS_UPDATED")]
        GroupAdminPermissionsUpdated,
        [Description("GROUP_CREATION")]
        GroupCreation,
        [Description("GROUP_DELETION")]
        GroupDeletion,
        [Description("GROUP_EDITED")]
        GroupEdited,
        [Description("GROUP_REMOVE_ITEM")]
        GroupRemoveItem,
        [Description("GROUP_REMOVE_USER")]
        GroupRemoveUser,
        [Description("ILLEGAL_ITEM_OWNERSHIP_TRANSFER_BY_USER")]
        IllegalItemOwnershipTransferByUser,
        [Description("ITEM_ASSOCIATION_CREATED")]
        ItemAssociationCreated,
        [Description("ITEM_ASSOCIATION_DELETED")]
        ItemAssociationDeleted,
        [Description("ITEM_ASSOCIATION_UPDATED")]
        ItemAssociationUpdated,
        [Description("ITEM_COPY")]
        ItemCopy,
        [Description("ITEM_CREATE")]
        ItemCreate,
        [Description("ITEM_DOWNLOAD")]
        ItemDownload,
        [Description("ITEM_EMAIL_SEND")]
        ItemEmailSend,
        [Description("ITEM_MAKE_CURRENT_VERSION")]
        ItemMakeCurrentVersion,
        [Description("ITEM_MODIFY")]
        ItemModify,
        [Description("ITEM_MOVE")]
        ItemMove,
        [Description("ITEM_OPEN")]
        ItemOpen,
        [Description("ITEM_PREVIEW")]
        ItemPreview,
        [Description("ITEM_RENAME")]
        ItemRename,
        [Description("ITEM_SHARED")]
        ItemShared,
        [Description("ITEM_SHARED_CREATE")]
        ItemSharedCreate,
        [Description("ITEM_SHARED_UNSHARE")]
        ItemSharedUnshare,
        [Description("ITEM_SHARED_UPDATE")]
        ItemSharedUpdate,
        [Description("ITEM_SYNC")]
        ItemSync,
        [Description("ITEM_TRASH")]
        ItemTrash,
        [Description("ITEM_UNDELETE_VIA_TRASH")]
        ItemUndeleteViaTrash,
        [Description("ITEM_UNSYNC")]
        ItemUnsync,
        [Description("ITEM_UPLOAD")]
        ItemUpload,
        [Description("LEGAL_HOLD_ASSIGNMENT_CREATE")]
        LegalHoldAssignmentCreate,
        [Description("LEGAL_HOLD_ASSIGNMENT_DELETE")]
        LegalHoldAssignmentDelete,
        [Description("LEGAL_HOLD_POLICY_CREATE")]
        LegalHoldPolicyCreate,
        [Description("LEGAL_HOLD_POLICY_DELETE")]
        LegalHoldPolicyDelete,
        [Description("LEGAL_HOLD_POLICY_UPDATE")]
        LegalHoldPolicyUpdate,
        [Description("LOCK")]
        Lock,
        [Description("LOCK_CREATE")]
        LockCreate,
        [Description("LOCK_DESTROY")]
        LockDestroy,
        [Description("LOGIN")]
        Login,
        [Description("MASTER_INVITE_ACCEPT")]
        MasterInviteAccept,
        [Description("MASTER_INVITE_REJECT")]
        MasterInviteReject,
        [Description("METADATA_CASCADE_POLICY_APPLY")]
        MetadataCascadePolicyApply,
        [Description("METADATA_CASCADE_POLICY_CREATE")]
        MetadataCascadePolicyCreate,
        [Description("METADATA_INSTANCE_COPY")]
        MetadataInstanceCopy,
        [Description("METADATA_INSTANCE_CREATE")]
        MetadataInstanceCreate,
        [Description("METADATA_INSTANCE_DELETE")]
        MetadataInstanceDelete,
        [Description("METADATA_INSTANCE_UPDATE")]
        MetadataInstanceUpdate,
        [Description("METADATA_TEMPLATE_CREATE")]
        MetadataTemplateCreate,
        [Description("METADATA_TEMPLATE_DELETE")]
        MetadataTemplateDelete,
        [Description("METADATA_TEMPLATE_UPDATE")]
        MetadataTemplateUpdate,
        [Description("MOVE")]
        Move,
        [Description("NEW_USER")]
        NewUser,
        [Description("OAUTH2_ACCESS_TOKEN_REVOKE")]
        Oauth2AccessTokenRevoke,
        [Description("OAUTH2_REFRESH_TOKEN_REVOKE")]
        Oauth2RefreshTokenRevoke,
        [Description("PREVIEW")]
        Preview,
        [Description("REMOVE_DEVICE_ASSOCIATION")]
        RemoveDeviceAssociation,
        [Description("REMOVE_LOGIN_ACTIVITY_DEVICE")]
        RemoveLoginActivityDevice,
        [Description("RENAME")]
        Rename,
        [Description("RETENTION_POLICY_ASSIGNMENT_ADD")]
        RetentionPolicyAssignmentAdd,
        [Description("SHARE")]
        Share,
        [Description("SHARED_LINK_REDIRECT_OUT_OF_SHARED_CONTEXT")]
        SharedLinkRedirectOutOfSharedContext,
        [Description("SHARED_LINK_SEND")]
        SharedLinkSend,
        [Description("SHARE_EXPIRATION")]
        ShareExpiration,
        [Description("SHIELD_ACCESS_POLICY_CREATED")]
        ShieldAccessPolicyCreated,
        [Description("SHIELD_ACCESS_POLICY_DELETED")]
        ShieldAccessPolicyDeleted,
        [Description("SHIELD_ACCESS_POLICY_UPDATED")]
        ShieldAccessPolicyUpdated,
        [Description("SHIELD_ALERT")]
        ShieldAlert,
        [Description("SHIELD_DOWNLOAD_BLOCKED")]
        ShieldDownloadBlocked,
        [Description("SHIELD_EXTERNAL_COLLAB_ACCESS_BLOCKED")]
        ShieldExternalCollabAccessBlocked,
        [Description("SHIELD_EXTERNAL_COLLAB_ACCESS_BLOCKED_MISSING_JUSTIFICATION")]
        ShieldExternalCollabAccessBlockedMissingJustification,
        [Description("SHIELD_EXTERNAL_COLLAB_INVITE_BLOCKED")]
        ShieldExternalCollabInviteBlocked,
        [Description("SHIELD_EXTERNAL_COLLAB_INVITE_BLOCKED_MISSING_JUSTIFICATION")]
        ShieldExternalCollabInviteBlockedMissingJustification,
        [Description("SHIELD_EXTERNAL_COLLAB_INVITE_JUSTIFIED")]
        ShieldExternalCollabInviteJustified,
        [Description("SHIELD_INFORMATION_BARRIER_COLLAB_BLOCKED")]
        ShieldInformationBarrierCollabBlocked,
        [Description("SHIELD_INFORMATION_BARRIER_DISABLED")]
        ShieldInformationBarrierDisabled,
        [Description("SHIELD_INFORMATION_BARRIER_ENABLED")]
        ShieldInformationBarrierEnabled,
        [Description("SHIELD_INFORMATION_BARRIER_GROUP_ADD_USER_BLOCKED")]
        ShieldInformationBarrierGroupAddUserBlocked,
        [Description("SHIELD_INFORMATION_BARRIER_ITEM_COPY_BLOCKED")]
        ShieldInformationBarrierItemCopyBlocked,
        [Description("SHIELD_INFORMATION_BARRIER_ITEM_MOVE_BLOCKED")]
        ShieldInformationBarrierItemMoveBlocked,
        [Description("SHIELD_INFORMATION_BARRIER_ITEM_OWNER_TRANSFER_BLOCKED")]
        ShieldInformationBarrierItemOwnerTransferBlocked,
        [Description("SHIELD_INFORMATION_BARRIER_PENDING")]
        ShieldInformationBarrierPending,
        [Description("SHIELD_INFORMATION_BARRIER_SHARED_ITEM_ACCESS_BLOCKED")]
        ShieldInformationBarrierSharedItemAccessBlocked,
        [Description("SHIELD_JUSTIFICATION_APPROVAL")]
        ShieldJustificationApproval,
        [Description("SHIELD_PREVIEW_BLOCKED")]
        ShieldPreviewBlocked,
        [Description("SHIELD_SHARED_LINK_ACCESS_BLOCKED")]
        ShieldSharedLinkAccessBlocked,
        [Description("SHIELD_SHARED_LINK_STATUS_RESTRICTED_ON_CREATE")]
        ShieldSharedLinkStatusRestrictedOnCreate,
        [Description("SHIELD_SHARED_LINK_STATUS_RESTRICTED_ON_UPDATE")]
        ShieldSharedLinkStatusRestrictedOnUpdate,
        [Description("SIGN_DOCUMENT_ASSIGNED")]
        SignDocumentAssigned,
        [Description("SIGN_DOCUMENT_CANCELLED")]
        SignDocumentCancelled,
        [Description("SIGN_DOCUMENT_COMPLETED")]
        SignDocumentCompleted,
        [Description("SIGN_DOCUMENT_CONVERTED")]
        SignDocumentConverted,
        [Description("SIGN_DOCUMENT_CREATED")]
        SignDocumentCreated,
        [Description("SIGN_DOCUMENT_DECLINED")]
        SignDocumentDeclined,
        [Description("SIGN_DOCUMENT_EXPIRED")]
        SignDocumentExpired,
        [Description("SIGN_DOCUMENT_SIGNED")]
        SignDocumentSigned,
        [Description("SIGN_DOCUMENT_VIEWED_BY_SIGNED")]
        SignDocumentViewedBySigned,
        [Description("SIGN_DOCUMENT_VIEWED_BY_SIGNER")]
        SignDocumentViewedBySigner,
        [Description("SIGNER_DOWNLOADED")]
        SignerDownloaded,
        [Description("SIGNER_FORWARDED")]
        SignerForwarded,
        [Description("STORAGE_EXPIRATION")]
        StorageExpiration,
        [Description("TAG_ITEM_CREATE")]
        TagItemCreate,
        [Description("TASK_ASSIGNMENT_CREATE")]
        TaskAssignmentCreate,
        [Description("TASK_ASSIGNMENT_DELETE")]
        TaskAssignmentDelete,
        [Description("TASK_ASSIGNMENT_UPDATE")]
        TaskAssignmentUpdate,
        [Description("TASK_CREATE")]
        TaskCreate,
        [Description("TASK_UPDATE")]
        TaskUpdate,
        [Description("TERMS_OF_SERVICE_ACCEPT")]
        TermsOfServiceAccept,
        [Description("TERMS_OF_SERVICE_REJECT")]
        TermsOfServiceReject,
        [Description("UNDELETE")]
        Undelete,
        [Description("UNFAVORITE")]
        Unfavorite,
        [Description("UNLOCK")]
        Unlock,
        [Description("UNSHARE")]
        Unshare,
        [Description("UPDATE_COLLABORATION_EXPIRATION")]
        UpdateCollaborationExpiration,
        [Description("UPDATE_SHARE_EXPIRATION")]
        UpdateShareExpiration,
        [Description("UPLOAD")]
        Upload,
        [Description("USER_AUTHENTICATE_OAUTH2_ACCESS_TOKEN_CREATE")]
        UserAuthenticateOauth2AccessTokenCreate,
        [Description("WATERMARK_LABEL_CREATE")]
        WatermarkLabelCreate,
        [Description("WATERMARK_LABEL_DELETE")]
        WatermarkLabelDelete,
        [Description("WORKFLOW_AUTOMATION_CREATE")]
        WorkflowAutomationCreate,
        [Description("WORKFLOW_AUTOMATION_DELETE")]
        WorkflowAutomationDelete,
        [Description("WORKFLOW_AUTOMATION_UPDATE")]
        WorkflowAutomationUpdate
    }
}